---
output:
  pdf_document: default
  html_document: default
---
```{r}
## Example 
# ---
# Question: Lets create a vector v
# ---
# OUR CODE GOES BELOW
# 
v <- c(1,3,5,8,2,1,3,5,3,5)

# Then determine whether this vector is a factor
# ---
#
is.factor(v)

```
```{r}
## Challenge 
# ---
# Question: Calculate the categorical distribution as shown and figure out why the given output
# ---
# OUR CODE GOES BELOW 
# 
factor(v)
```
```{r}
## Example 
# ---
# Question: Assign factor v tox and print out x 
# ---
# OUR CODE GOES BELOW 
# 
x <- factor(v)
x
```
```{r}
## Challenge 
# ---
# Question: Determine whether x is a factor below. 
# Hint: Just like the way you did when you were finding out whether vector v is a factor
# ---
is.factor(x)
```
```{r}
#### 1.2 Factors Code Example 

## Example 
# ---
# Question: First we create a vector as input, check whether its a factor, 
# apply the factor function to create a factor from the vector
# ---
# OUR CODE GOES BELOW
# 
data <- c("East","West","East","North","North","East","West","West","West","East","North")
# Then print out this vector
data
# Now, check whether this is a factor
is.factor(data)
# Then, apply the factor function to create a factor from the vector
factor_data <- factor(data)
# Then see our newly created factor
factor_data
# Check whether this is a factor
is.factor(factor_data)
```
```{r}
#### 1.3 Factors Code Example

# Example  
# ---
# Creating a factor, determine and check the levels 
# ---
# OUR CODE GOES BELOW
# 
sex <- factor(c("male", "female", "female", "male"))
# Determining the levels
levels(sex)
# Then checking the number of levels using nlevels()
nlevels(sex)

# Sometimes, the order of the factors does not matter, other times you might want to specify the order 
# because it is meaningful (e.g., “low”, “medium”, “high”) or it is required by particular type of analysis. 
# Additionally, specifying the order of the levels allows us to compare levels:
food <- factor(c("low", "high", "medium", "high", "low", "medium", "high"))

# then print out levels of food
levels(food)
```
```{r}
## 2. Data Frames
### Creating a Dataframe 

#### 2.1 Creating a Dataframe Code Example

## Example 
# ---
# Question: Lets create a data frame BMI
# ---
# OUR CODE GOES BELOW
# 
BMI <- data.frame( 
    gender  = c("Male", "Male","Female"), 
    height  = c(152, 171.5, 165), 
    weight  = c(81,93, 78), 
    Age     = c(42,38,26)
) 

# Then print it out below
BMI
```
```{r}
### Selecting Elements From a DataFrame 

#### 2.2 Selecting Elements From a DataFrame Code Example

## Example 
# ---
# Question: Selecting elements from the BMI dataframe
# ---
# OUR CODE GOES BELOW
# 

# selecting row 1 
BMI[1,]

# selecting rows 1 to 2
BMI[1:2, ] 

# selecting column 1 
BMI[,1]

# selecting column 1 to 2
BMI[,1:2 ] 

# selecting row 1 in column 2
BMI[1,2] 
```
```{r}
## Challenge 
# ---
# Question: Select the column 2 from the BMI dataframe
# ---
# OUR CODE GOES BELOW
# 

BMI[,2]
```
```{r}
### Sorting

#### 2.3 Sorting Code Example
## Example 
# ---
# Question: Sort the BMI dataframe by using the order() function 
# ---
# 

# Sort in ascending order by gender
# ---
#
sorted_by_gender <- BMI[order(BMI$gender),]

# Print out sorted_by_gender below
# ---
#
sorted_by_gender

# Sort in descending order by weight
# ---
# 
sorted_by_weight <- BMI[order(-BMI$weight),]

# Print out sorted_by_weight below
# ---
# 
sorted_by_weight
```
```{r}
## 3. Data Tables

### Creating a Data Table

#### 3.2 Creating a Data Table Code Example

## Example 
# ---
# Question: Create a data table DT
# ---
# 
# Load the data.table package
# ---
# 
library(data.table)

DT = data.table(
  ID = c("b","b","b","a","a","c"),
  a = 1:6,
  b = 7:12,
  c = 13:18
)

DT

```
```{r}
### Selecting Elements From a Data Table

#### 3.3 Selecting Elements From a Data Table Code Example

## Example 
# ---
# Question: Select elements from the given datatable DT
# ---
# OUR CODE GOES BELOW
# 

# Selecting Row 1 
DT[1,]

# Selecting Rows 1 to 2
DT[1:2,] 

# Find out what happens when we print out the following statement 
DT[,1]

# Find out what happens when we print out the following statement
DT[,1:2] 

# And lastly find out what happens when we print out the following statement
DT[1,2] 
```
```{r}
# Select the fourth and third rows from the data table

DT[3:4,]
```
```{r}
### Sorting a Data Table

#### 3.4 Sorting a Data Table Code Example

## Example 
# ---
# Question: Sorting the datatable in ascending order by c 
# ---
# OUR CODE GOES BELOW
# 

# Performing the sort
# 
sorted_by_c <- DT[order(DT$c),]

# Printing out sorted_by_c
sorted_by_c
```
```{r}
# Sort in descending order by b, uncommenting the line below
# ---
# 
sorted_by_b <- DT[order(-DT$b),]
sorted_by_b
```
```{r}
## 4. Tibbles

### Creating a Tibble

#### 4.1 Creating a Tibble Code Example

## Example 
# ---
# Question: Create a tible tb
# ---
# OUR CODE GOES BELOW
# 

# First, we load the tibble package
library(tibble)

# Then create our tibble tb
tb <- tibble(
  x = 1:5, 
  y = 1, 
  z = x ^ 2 + y
)

# And finally print the created tibble 
# ---
# OUR CODE GOES BELOW
#
tb
```
```{r}
### Selecting a Tibble Code Example

#### 4.1 Selecting a Tibble Code Example

## Example 
# ---
# Question: Find out what happens when we print the following 
# ---
# OUR CODE GOES BELOW
# 
tb[1,]
tb[1:2, ] 
tb[,1]
tb[,1:2 ] 

# Select the second and third rows
# ---
# OUR CODE GOES BELOW
# 
tb[2:3, ]
```
```{r}
### Sorting a Tibble

#### 4.1 Sorting a Tibble Code Example

## Example
# ---
# Question: Find out what happens when we sort by doing the following 
# ---
# 
sorted_by_1 <- tb[order(tb$z),]
sorted_by_1

sorted_by_2 <- tb[order(-tb$x),]
sorted_by_2
```
```{r}
# Sort tb in ascending order by x below
# ---
# OUR CODE GOES BELOW
# 
sorted_by_3 <- tb[order(tb$x),]
sorted_by_3
```






















